"use client";
import { ChangeEvent, useMemo, useState } from "react";
import { FileSpreadsheet, Upload, X } from "lucide-react";
import { autoMapColumns, parseCsvText, parseImportFile, processImportRows, type ImportRow } from "@/lib/collection-importer";
import { supabase } from "@/lib/supabase";
import type { Collection } from "@/lib/types";

type Source = "excel" | "google_sheets" | "manual";
const idFromName = (name: string) => `${name.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/đ/g, "d").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}-${Date.now().toString(36)}`;

export function CollectionImportModal({ onClose, onDone }: { onClose: () => void; onDone: () => Promise<void> | void }) {
  const [source, setSource] = useState<Source>("excel"); const [name, setName] = useState(""); const [icon, setIcon] = useState("🍜"); const [owner, setOwner] = useState(""); const [type, setType] = useState<"food" | "cafe">("food");
  const [sheetUrl, setSheetUrl] = useState(""); const [rows, setRows] = useState<ImportRow[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const headers = useMemo(() => rows[0] ? Object.keys(rows[0]) : [], [rows]); const mapping = useMemo(() => autoMapColumns(headers), [headers]);
  const loadRows = (nextRows: ImportRow[]) => { setRows(nextRows); setMessage(nextRows.length ? `Đã nhận diện ${nextRows.length} dòng.` : "Không tìm thấy dòng dữ liệu."); };
  const onFile = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; try { loadRows(await parseImportFile(file)); } catch { setMessage("Không thể đọc file này."); } };
  const loadSheet = async () => { setBusy(true); try { const response = await fetch(`/api/sync-sheet?url=${encodeURIComponent(sheetUrl)}`); const text = await response.text(); if (!response.ok) throw new Error(JSON.parse(text).error); loadRows(parseCsvText(text)); } catch (error) { setMessage(error instanceof Error ? error.message : "Không tải được Sheet."); } finally { setBusy(false); } };
  const submit = async () => { if (!supabase || !name.trim()) return setMessage("Hãy nhập tên nguồn."); setBusy(true); try { const collection: Collection = { id: idFromName(name), name: name.trim(), icon: icon || "🍜", owner_name: owner.trim() || "Prot", type, source_type: source, google_sheets_url: source === "google_sheets" ? sheetUrl : null };
    const { error } = await supabase.from("collections").insert(collection); if (error) throw new Error(error.message); const count = source === "manual" ? 0 : await processImportRows(rows, collection.id, mapping, (done, total) => setMessage(`Đang nạp ${done}/${total}…`)); await onDone(); setMessage(`Đã tạo nguồn và nạp ${count} quán.`); window.setTimeout(onClose, 900);
  } catch (error) { setMessage(error instanceof Error ? error.message : "Không thể nạp dữ liệu."); } finally { setBusy(false); } };
  return <div className="fixed inset-0 z-[80] flex items-end justify-center bg-black/40 p-0 backdrop-blur-sm md:items-center md:p-5"><section className="max-h-[94dvh] w-full max-w-2xl overflow-y-auto rounded-t-[28px] bg-[#fbf3ea] p-5 shadow-2xl dark:bg-[#281b13] md:rounded-[28px]"><div className="flex items-center justify-between"><div><p className="text-xs font-extrabold tracking-wider text-[#a35e2d]">ADMIN PROT</p><h2 className="text-xl font-extrabold">Nạp nguồn dữ liệu</h2></div><button type="button" onClick={onClose} className="rounded-xl p-2"><X /></button></div>
    <div className="mt-4 flex gap-2 overflow-x-auto">{(["excel", "google_sheets", "manual"] as Source[]).map((item) => <button type="button" key={item} onClick={() => setSource(item)} className={`rounded-xl px-3 py-2 text-xs font-bold ${source === item ? "bg-[#402c1e] text-white" : "bg-[#402c1e]/8"}`}>{item === "excel" ? "📂 Excel / CSV" : item === "google_sheets" ? "🌐 Google Sheets" : "✏ Tạo thủ công"}</button>)}</div>
    <div className="mt-5 grid gap-3 sm:grid-cols-2"><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Tên nguồn *" className="rounded-xl border bg-white/70 px-3 py-2.5 dark:bg-black/10"/><input value={owner} onChange={(e) => setOwner(e.target.value)} placeholder="Người chia sẻ" className="rounded-xl border bg-white/70 px-3 py-2.5 dark:bg-black/10"/><input value={icon} onChange={(e) => setIcon(e.target.value)} placeholder="Icon" className="rounded-xl border bg-white/70 px-3 py-2.5 dark:bg-black/10"/><select value={type} onChange={(e) => setType(e.target.value as "food" | "cafe")} className="rounded-xl border bg-white/70 px-3 py-2.5 dark:bg-black/10"><option value="food">Đồ ăn</option><option value="cafe">Cafe / đồ uống</option></select></div>
    {source === "excel" && <label className="mt-4 flex cursor-pointer flex-col items-center rounded-2xl border-2 border-dashed border-[#a35e2d]/40 p-7 text-center text-sm font-bold"><FileSpreadsheet className="mb-2 text-[#a35e2d]"/>Kéo thả hoặc bấm chọn .xlsx, .xls, .csv<input type="file" accept=".xlsx,.xls,.csv" onChange={onFile} className="hidden"/></label>}
    {source === "google_sheets" && <div className="mt-4 flex gap-2"><input value={sheetUrl} onChange={(e) => setSheetUrl(e.target.value)} placeholder="Dán link Google Sheets công khai" className="min-w-0 flex-1 rounded-xl border bg-white/70 px-3 py-2.5 dark:bg-black/10"/><button type="button" disabled={busy || !sheetUrl} onClick={loadSheet} className="rounded-xl bg-[#402c1e] px-3 text-xs font-bold text-white">🔄 Đồng bộ lại</button></div>}
    {rows.length > 0 && <div className="mt-4 overflow-x-auto rounded-xl border p-3"><p className="text-xs font-bold">Preview · {mapping.name ? `cột tên: ${mapping.name}` : "chưa nhận diện cột tên"}</p><table className="mt-2 min-w-full text-left text-xs"><tbody>{rows.slice(0, 5).map((row, index) => <tr key={index} className="border-t"><td className="py-2 pr-3 font-bold">{String(row[mapping.name || headers[0]] ?? "")}</td><td className="py-2">{String(row[mapping.address || headers[1]] ?? "")}</td></tr>)}</tbody></table></div>}
    {message && <p className="mt-3 text-sm text-[#8a7360]">{message}</p>}<div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-xl px-4 py-2 text-sm font-bold">Hủy</button><button type="button" disabled={busy || !name.trim() || (source !== "manual" && !rows.length)} onClick={submit} className="rounded-xl bg-[#a35e2d] px-4 py-2 text-sm font-extrabold text-white disabled:opacity-50"><Upload className="mr-1 inline" size={15}/>{busy ? "Đang nạp…" : "Bắt đầu nạp"}</button></div>
  </section></div>;
}
